### ISSUE TITLE
How do I add the AppSDK framework packages to an msixbundle?

### ISSUE THREAD

**Issue by wjk** [microsoft/WindowsAppSDK#3579]
### Describe the bug

I am using MSIX deployment for my app. I have used [some custom code](https://github.com/wjk/WindowsLogViewer/blob/main/build/targets/MsixBundle.targets) to build an msixbundle file, since AppSDK does not do that by itself. The MSIX packages inside contain a `<PackageDependency>` on the AppSDK framework. I can find the MSIX files for the framework under my bin directory. I need to be able to add all required packages to my msixbundle so that it can install and launch on a clean system from that one file, without any other dependencies. Please be aware that I am targeting both x64 and ARM64, so the two architectures would need to coexist.

### Steps to reproduce the bug

Explained above.

### Expected behavior

I should be able to do this.

### NuGet package version

Windows App SDK 1.3.0: 1.3.230331000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by wjk** [comment]
> To put it another way, the Microsoft project type which does everything correctly doesn't add the dependencies to the bundle either.

Then how should I distribute the relevant MSIXs so that the system does not have to download files from the Windows Store? I remember reading on docs that if you do not distribute MSIXs through the Windows Store, I am responsible for installing the relevant framework packages myself. Is there a good way to do this?

**Comment by DarranRowe** [comment]
To be honest, I think the easiest way is by using a .appinstaller file.
If you put the files onto a network share or internal web server then you can distribute things that way. As an example for a simple packaged C++ application, I have:

```
<?xml version="1.0" encoding="utf-8"?>
<AppInstaller Uri="file://server/msix/BasicWindowTest.appinstaller" Version="1.0.0.0" xmlns="http://schemas.microsoft.com/appx/appinstaller/2021">

  <MainBundle Name="Untrusted.BasicWindowTest" Version="1.0.0.0" Publisher="CN=Darran" Uri="file://server/msix/BasicWindowTestPackage_1.0.0.0_Test/BasicWindowTestPackage_1.0.0.0_x86_x64_arm64.msixbundle"/>
  <Dependencies>
    <Package Name="Microsoft.VCLibs.140.00.UWPDesktop" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="arm64" Uri="file://server/msix/Dependencies/arm64/Microsoft.VCLibs.ARM64.14.00.Desktop.appx" Version="14.0.30704.0"/>
    <Package Name="Microsoft.VCLibs.140.00.UWPDesktop" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="x64" Uri="file://server/msix/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx" Version="14.0.30704.0"/>
    <Package Name="Microsoft.VCLibs.140.00.UWPDesktop" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="x86" Uri="file://server/msix/Dependencies/x86/Microsoft.VCLibs.x86.14.00.Desktop.appx" Version="14.0.30704.0"/>

    <Package Name="Microsoft.WindowsAppRuntime.1.3" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="arm64" Uri="file://server/msix/Dependencies/arm64/Microsoft.WindowsAppRuntime.1.3.msix" Version="3000.820.152.0" />
    <Package Name="Microsoft.WindowsAppRuntime.1.3" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="x64" Uri="file://server/msix/Dependencies/x64/Microsoft.WindowsAppRuntime.1.3.msix" Version="3000.820.152.0" />
    <Package Name="Microsoft.WindowsAppRuntime.1.3" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="x86" Uri="file://server/msix/Dependencies/x86/Microsoft.WindowsAppRuntime.1.3.msix" Version="3000.820.152.0" />

    <Package Name="Microsoft.VCLibs.140.00" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="arm64" Uri="file://server/msix/Dependencies/arm64/Microsoft.VCLibs.ARM64.14.00.appx" Version="14.0.30704.0" />
    <Package Name="Microsoft.VCLibs.140.00" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="x64" Uri="file://server/msix/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx" Version="14.0.30704.0" />
    <Package Name="Microsoft.VCLibs.140.00" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" ProcessorArchitecture="x86" Uri="file://server/msix/Dependencies/x86/Microsoft.VCLibs.x86.14.00.appx" Version="14.0.30704.0" />
  </Dependencies>

</AppInstaller>
```

Anyway, double clicking on this type of file will open up the app installer. You use this to tell the installer where to find all of the dependencies and the app installer will then use these if the dependency doesn't exist. If you add a template .appinstaller file to the packaging project and enable automatic updates, Visual Studio will even generate this for you.

The only with this file is that it doesn't lend itself to being used to install files off of a USB drive. The paths given in the URI attributes are fixed meaning that you either have to guarantee that the drive will always use the same drive letter, or you use some means to dynamically generate the .appinstaller based on the current system's drive letters. From what I can tell though, as long as it is an absolute path, the file scheme should work even for a local path.

**Comment by DrusTheAxe** [comment]
A .appinstaller file is the right way. BTW you can embed a .appinstaller file in your package (aka Auto-Update) for the same net result as a separate file but provided by the developer (not the distributor or administrator). There's also APIs for admin overrides for even more flexibility. Sorry, no net access at the moment but if you search for "msix auto-update appinstaller embed" you should find the docs how to do this.

The reason This Is The Way is a .msixbundle contains pckages for *a* package family. A bundle can contain multiple main and resource packages for a family (x86,arm64,en,fr,scale-100,...) but all the same package family name. WinAppSDK framework packages will have a different family name.

What brought this to mind?

I ask as Flat bundles were created based on feedback requesting a way to not have to "make a super zip-of-zips" if you will. A Flat bundle as basically a list of packages collocated with defined dependencies, if you add the notion of "and here's where you can find the dependencies" you get the same net result of .appinstaller files and AutoUpdate.

A bundle as 1 container of multiple packages *and their dependencies* is akin to going in the opposite direction, which poses issues which led us to pave ground towards rich but more physically decoupled options. So I'm interested in your thoughts that led to this conversation 🙂

**Comment by wjk** [comment]
> What brought this to mind?

Mostly because I didn’t know what you’ve just explained to me.

I was considering using MSIX packages to distribute apps that I might write in the future. If there were one file to download, it would be easier to explain to users how to install the program. (I would have to wrap the packages in an EXE because I still cannot afford a commercial code-signing certificate. I find it odd that you can have a package with no signature whatsoever, but self-signed certificates are still prohibited. Self-signed certs are just as secure as commercial ones. If the user trusts my app and company, it shouldn’t matter what kind of certificate I use.)

However, since I first filed this issue I reconsidered the Windows Store. Despite what I see as design flaws with `Windows.Services.Store`, it is still a better place for me to distribute my apps than just another website. (There’s more discoverability, I wouldn’t need a CDN, and billing and licensing would be handled for me.) With the Windows Store, all this is a nonissue. Thanks nonetheless!

**Comment by DrusTheAxe** [comment]
Glad you found a path that works for you :-)
