### ISSUE TITLE
After updating Windows 10, Windows can no longer manage any appx packages, and I can't deploy WinUI 3 apps from VS

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/WindowsAppSDK#4881]
I just updated ~Visual Studio to 17.13.0 Preview 1 and~ Windows to 19045.5131.

Now Visual Studio can no longer deploy WinUI 3 apps, I can't uninstall any apps, the Microsoft Store can't update any apps, and trying a different account also results in the Store malfunctioning.

It seems Windows has lost its ability to manage packages.

@DrusTheAxe From what I've seen you are an expert in this area. Any suggestions for how to approach this?

VS error is:

```
DEP0900: Failed to unregister application "myappid". [0x80073CFA] 
```

**Comment by Xo3-ToBapbl** [comment]
Can confirm. All our devs with win10 22H2 19045.5131, 19045.5011 machines faced with this issue. No problems for devs with win11 23H2 and above.

Just quick note, I think Visual Studio update is not the reason of this issue. We faced it on VS 17.9.7.

Related .NET MAUI topic:
https://github.com/dotnet/maui/issues/25832

**Comment by sigroli** [comment]
We experienced the same issue and identified Windows update KB5046613 as the cause.

**Comment by riesem** [comment]
Can confirm KB5046613 as cause but uninstalling does not help

**Comment by kmgallahan** [comment]
Every time. 

"I think I'll update some packages. I may as well update VS while I'm at it. Oh, it suggests a restart. Ah, Windows wants to update during the restart."

~

"I wonder how much time & money this is going to cost me."

---

Only "solution" I've found is a clean install, which isn't a solution at all. Maybe now that millions are impacted Microsoft will throw together some sort of fix...

**Comment by S4nt1ag0** [comment]
Same problem here, how you "clean install" ? i am noobie in C# development.  Do you click "Clean Solution" and Rebuild ?

**Comment by ivanjx** [comment]
@S4nt1ag0 clean install the whole OS

**Comment by robertbrestle** [comment]
I'm currently having this issue on Win10 22H2 builds `19045.5011` and `19045.5131`. We started noticing this issue on 11/12.

**Comment by subratb** [comment]
Please look at [this](https://techcommunity.microsoft.com/discussions/azurevirtualdesktopforum/azure-virtual-desktop---black-screens-on-logins---what-weve-tried-so-far/4250228/replies/4259588#M12793). The discussion started [here ](https://answers.microsoft.com/en-us/windows/forum/all/remove-appxpackage-allusers-causes-application/221b3122-56be-4140-9764-6765cf461e4d?page=1)and lead up to the [stated](https://techcommunity.microsoft.com/discussions/azurevirtualdesktopforum/azure-virtual-desktop---black-screens-on-logins---what-weve-tried-so-far/4250228/replies/4259588#M12793) solution.

**Comment by kmgallahan** [comment]
@subratb That looks like a different issue, and it is a month old. This one is brand new this week.

**Comment by StevoSM** [comment]
Experiencing the same here.  Pretty much dead in the water until a fix is released.  All development has been blocked.

**Comment by kmgallahan** [comment]
@StevoSM You can just stick this in your csproj files to make them unpackaged until a fix is available - unless they require something only packages support.

```
        <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
        <WindowsPackageType>None</WindowsPackageType>
```

**Comment by johnt-star** [comment]
I am now having same issue.

I added the above lines to my project file, first in an existing property group, now in their own as follows:
  <PropertyGroup>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

Restarted Visual Studio, did a Clean and Rebuild Solution, but still get
![Image](https://github.com/user-attachments/assets/fba8a334-5a9d-4346-b530-89f11e6261b4)

even though deploy option is set
![Image](https://github.com/user-attachments/assets/38673ab6-e851-4ac7-94dd-27a79bb1bb99)

**Comment by kmgallahan** [comment]
@johnt-star You need to change your configuration selection to Unpackaged.

![Image](https://github.com/user-attachments/assets/a8ab5f4c-1001-4987-976b-4b4cb04d70cd)

**Comment by johnt-star** [comment]
Thanks kmgallahan!

I no longer get the deployment error dialog after changing to Unpackaged.

Unfortunately after upgrading Visual Studio to the latest version, updating nuget packages where appropriate and installing .Net 9, I am now getting exceptions for things that use to work.

At least I can see what has changed and hopefully resolve them in order to get my app running again.

Appreciate the help!

**Comment by kmgallahan** [comment]
One thing I had to do was add this to resolve some ref issues:

``` .xml
<OutputPath>$(SolutionDir)bin\$(Configuration)\</OutputPath>
```

**Comment by codendone** [comment]
There was an issue in the WinAppSDK 1.6.2 release which affected Windows 10 version 19045 machines. The 1.6.2 release has been pulled to prevent more machines being impacted.

This issue was not caused by an update to Windows and will not be fixed by uninstalling any Windows Cumulative Updates.

There is an upcoming Windows Update which will fix this issue (adding extra safety in Windows), and a release of WinAppSDK 1.6.3 is coming soon with a fix.

Machines in a bad state can also be manually fixed by running these steps:
1. Launch a PowerShell or Command Prompt as Administrator and run these commands:
```
takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant Administrators:F
del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant Administrators:F
del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
```
2. Reboot
3. Launch a PowerShell as Administrator and run these commands:
```
Get-AppxPackage *WinAppRuntime.Main.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
Get-AppxPackage *MicrosoftCorporationII.WinAppRuntime.Singleton* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
Get-AppxPackage *Microsoft.WinAppRuntime.DDLM* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
Get-Appxpackage *WindowsAppRuntime.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
Investigations are continuing and we'll provide further updates when available.
```

If you have an app project referencing the `Microsoft.WindowsAppSDK` package version `1.6.241106002`, update the project to instead reference version `1.6.240923002`. Removing version `1.6.241106002` from your local NuGet cache (such as `C:\Users\<username>\.nuget\packages\microsoft.windowsappsdk\1.6.241106002`) is also recommended to avoid accidental usage.

**Comment by StevoSM** [comment]
@codendone Thanks for the update.  I don't know how helpful this might be, but we are only on WinAppSDK 1.4 and are experiencing the issue.  We have not yet updated to 1.6 at all.  In our environment, it must be the result of a Windows update or possibly that combined with a Visual Studio 2022 update.

**Comment by codendone** [comment]
@StevoSM There must be a different app on the system which is using 1.6. Running `Get-Appxpackage *WindowsAppRuntime.1.6* -AllUsers` in an administrative PowerShell can help see those.

**Comment by StevoSM** [comment]
@codendone Apparently so.  Your command revealed 3 results, 2 of which matched the problematic version.  I went through your suggestion above and, well, it worked and we're back in business!  Thanks so much for your hard work on this and posting those steps!

**Comment by Balkoth** [comment]
@codendone 
Your commands only work on an english OS. Once i got the first block working by replacing "Administrators" with the localized version i am stuck on step 3:

```
PS C:\WINDOWS\system32> Get-Appxpackage *WindowsAppRuntime.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
Remove-AppxPackage : Der Remoteprozeduraufruf ist fehlgeschlagen.
Der Remoteprozeduraufruf ist fehlgeschlagen.
In Zeile:1 Zeichen:96
+ ... ere { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
+                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand
```

What now?

**Comment by kimpel70** [comment]
> [@codendone](https://github.com/codendone) Your commands only work on an english OS. Once i got the first block working by replacing "Administrators" with the localized version i am stuck on step 3:
> 
> ```
> PS C:\WINDOWS\system32> Get-Appxpackage *WindowsAppRuntime.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> Remove-AppxPackage : Der Remoteprozeduraufruf ist fehlgeschlagen.
> Der Remoteprozeduraufruf ist fehlgeschlagen.
> In Zeile:1 Zeichen:96
> + ... ere { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> +                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
>     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand
> ```
> 
> What now?

@Balkoth ,
i'm also running into this problem, and thanks for the tip regarding 'Adminstratoren'. The solution to your problem is, to copy each line individually and run them through powershell, not the whole block at once.

**Comment by kimpel70** [comment]
@codendone,
FYI, it is still possible to download the SDK 1.6.2 manually: https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads.
I got to this place, getting the following message (containing the link) while trying to deploy a MauiApp in Visual Studio 2022 for debugging.

```
DEP0840: Project 'MauiApp.Maui' requires packages 'MicrosoftCorporationII.WinAppRuntime.Main.1.5_8wekyb3d8bbwe' and 'MicrosoftCorporationII.WinAppRuntime.Singleton_8wekyb3d8bbwe' with version >= '5001.178.1908.0'. These packages should be installed on first run, if not please visit http://go.microsoft.com/fwlink/?linkid=2222757 for installation instructions.
```

**Comment by nidietr-MSFT** [comment]
> [@codendone](https://github.com/codendone) Your commands only work on an english OS. Once i got the first block working by replacing "Administrators" with the localized version i am stuck on step 3:
> 
> ```
> PS C:\WINDOWS\system32> Get-Appxpackage *WindowsAppRuntime.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> Remove-AppxPackage : Der Remoteprozeduraufruf ist fehlgeschlagen.
> Der Remoteprozeduraufruf ist fehlgeschlagen.
> In Zeile:1 Zeichen:96
> + ... ere { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> +                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
>     + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Commands.RemoveAppxPackageCommand
> ```
> 
> What now?

@Balkoth, this "Remote Procedure Call Failed" error comes from another issue causing AppxSvc crashes during package removal, which was fixed starting the optional update end of October (https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-10-22h2#3421msgdesc). Best would be to deploy the cumulative update from November 2024 (https://support.microsoft.com/en-us/topic/november-12-2024-kb5046613-os-builds-19044-5131-and-19045-5131-44e6c27e-e188-4dd5-8ad2-edde2e235c01).

**Comment by baaaaif** [comment]
The really big problem is that existing app installations that are used productively can no longer be started by customers.
An admin now has to implement the workaround for hundreds of users. The Windows Update is therefore needed as soon as possible.
And the productive installations use an SDK 1.5.x version, not 1.6

**Comment by MarkRichardsACN** [comment]
@codendone we have a number of people at our company (including one of my machines) that have this.  We do not have local admin rights, so I can't run the script steps you posted above.  Btw, for us it is an Maui MSIX installed via Software Center, not the windows store.

When the SDK 1.6.3 comes out, will it "fix" broken machines, or will all affected users have to run your steps above ?

Thanks,
Mark

**Comment by codendone** [comment]
WinAppSDK 1.6.3 is now available, providing access to the improvements in 1.6.2 minus the issue. This release does not fix any machine which is already in the bad state.
 
We're working on a better way to fix broken machines and will provide an update when available.

**Comment by IstvanKor** [comment]
In our case this issue happens not only to WinAppSDK applications, but also when installing/uninstalling UWP applications as well. Trying  to uninstall a UWP application we got 0x80073CFA error. Trying to install the same  app we got "Remote Procedure Call Failed" error. We were facing this issue after applying KB5046613 update to win10 22H2. The problem occurs on the win 10 client machine, not on the dev machine. Development device is a win 11 pc in my case.
https://answers.microsoft.com/en-us/windows/forum/all/error-code-0x80073cfa-while-trying-to-uninstall-or/f74cc104-4aa7-4394-853c-7185b5275923

**Comment by danielancines** [comment]
> There was an issue in the WinAppSDK 1.6.2 release which affected Windows 10 version 19045 machines. The 1.6.2 release has been pulled to prevent more machines being impacted.
> 
> This issue was not caused by an update to Windows and will not be fixed by uninstalling any Windows Cumulative Updates.
> 
> There is an upcoming Windows Update which will fix this issue (adding extra safety in Windows), and a release of WinAppSDK 1.6.3 is coming soon with a fix.
> 
> Machines in a bad state can also be manually fixed by running these steps:
> 
> 1. Launch a PowerShell or Command Prompt as Administrator and run these commands:
> 
> ```
> takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant Administrators:F
> del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant Administrators:F
> del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> ```
> 
> 2. Reboot
> 3. Launch a PowerShell as Administrator and run these commands:
> 
> ```
> Get-AppxPackage *WinAppRuntime.Main.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> Get-AppxPackage *MicrosoftCorporationII.WinAppRuntime.Singleton* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> Get-AppxPackage *Microsoft.WinAppRuntime.DDLM* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> Get-Appxpackage *WindowsAppRuntime.1.6* -AllUsers | Where { $_.Version -eq '6000.311.13.0' } | Remove-AppxPackage -AllUsers
> Investigations are continuing and we'll provide further updates when available.
> ```
> 
> If you have an app project referencing the `Microsoft.WindowsAppSDK` package version `1.6.241106002`, update the project to instead reference version `1.6.240923002`. Removing version `1.6.241106002` from your local NuGet cache (such as `C:\Users\<username>\.nuget\packages\microsoft.windowsappsdk\1.6.241106002`) is also recommended to avoid accidental usage.
> 
> Investigations are continuing and we'll provide further updates when available.

First step worked for my Store Apps like WhatsApp, thank you.

**Comment by paul-d-ray** [comment]
Thank you.

Winget stopped working today after working yesterday.
I came across this when searching for the error code.

I did step one and Winget now works.

**Comment by dkuenne** [comment]
> Machines in a bad state can also be manually fixed by running these steps:
> 
>     1. Launch a PowerShell or Command Prompt as Administrator and run these commands:
> ```
> takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant Administrators:F
> del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant Administrators:F
> del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
> ```

For non-english localized systems the [SID](https://learn.microsoft.com/en-us/windows/win32/secauthz/well-known-sids) can be used:
```
takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant "$((Get-LocalGroup -SID S-1-5-32-544).Name):F"
del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
takeown /F "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
icacls "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll" /grant "$((Get-LocalGroup -SID S-1-5-32-544).Name):F"
del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x86__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"
```

**Comment by codendone** [comment]
A simpler solution to fix a machine in a bad state is to run the WinAppSDK 1.6.3 installer multiple times. The installer is available at [Latest downloads for the Windows App SDK - Windows apps | Microsoft Learn](https://learn.microsoft.com/windows/apps/windows-app-sdk/downloads), with this as right installer for most machines:
* [Installer (x64)](https://aka.ms/windowsappsdk/1.6/1.6.241114003/windowsappruntimeinstall-x64.exe)

Run that installer, which will fail the first time it is run. Run it again which usually succeeds. If necessary, run it again until it succeeds.
 
We're continuing work on a better fix for broken machines and will provide an update when available.

**Comment by GeoSaffer** [comment]
Thank you SOOOOOO much @codendone , this work great !!!!!

**Comment by developertest02** [comment]
Thank you. This was the only thing that worked.

**Comment by King-Taz** [comment]
Does not work for me using Windows 11. Deploy box still grayed out in VS. Tried to install multiple times, got this return.
```
Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0
All install operations successful.
```

**Comment by ClausAndersen** [comment]
> > del "C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.6_6000.311.13.0_x64__8wekyb3d8bbwe\WindowsAppRuntime.DeploymentExtensions.OneCore.dll"

I had problems deleting this file. It turned about to be because it was in use. That was fixed by stopping the service first:

    sc stop AppXSVC

**Comment by ClausAndersen** [comment]
I can confirm the 1.6.3 does remove the 0x80073CFA error. It does however cause related issues. I cannot re-install Windows Terminal or winget as I am told I already have a newer version. I suspect that these are built as self contained bundles and the bundles then need to be updated with a later version of the SDK. But I cannot confirm this.

See [microsoft/winget-cli/issues/4991](https://github.com/microsoft/winget-cli/issues/4991) and [microsoft/terminal/issues/18237](https://github.com/microsoft/terminal/issues/18237).

So this seems to be related fallout. It would be nice if we could get confirmation if it would help these issues if they create new builds using the 1.6.3 SDK redistributable?

**Comment by kumaresan-cgvak** [comment]
Microsoft released a patch OS update for Windows 10 with the fix for the install / uninstall issue.

[Users might be unable to update or uninstall packaged apps on Windows 10](https://learn.microsoft.com/en-us/windows/release-health/resolved-issues-windows-10-22h2#3447msgdesc)

Updating the OS to the Below optional update will allow the user to uninstall in case if the corrupted version of the app is there. in certain cases, it automatically removes the corrupted app. allowing us to do a fresh install of the app again.

![Image](https://github.com/user-attachments/assets/e531e821-9c18-44e0-9e43-ab107f51b0ac)

**Comment by codendone** [comment]
This discussion post is now available with the summary of the situation and recommended resolutions: #4913. Any further updates will be posted there.

**Comment by codendone** [comment]
Closing this issue as fixed/mitigated.
